version: "3.9"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

        #db:
        #  image: postgres:latest
        #  volumes:
        #    - db:/var/lib/postrgresql/data/
        #  ports:
        #    - "5432:5432"
        #  environment:
        #    POSTGRES_PASSWORD: mysecretpassword
        #    POSTGRES_DB: example-pg-docker
        #  healthcheck:
        #    test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U postgres"]
        #    interval: 10s
        #    timeout: 5s
        #    retries: 10
        #    start_period: 3s

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 3s
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  app:
    build:
      context: .
      args:
        INSTALL_DEPENDENCIES: dev
    depends_on:
      redis:
        condition: service_started
          #db:
          #  condition: service_healthy

    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - .:/app:cached

networks:
  postgres:
    driver: bridge

volumes:
  db: {}
  cache: {}
  postgres:
  pgadmin:
